routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::post('/proses-login', [LoginController::class, 'prosesLogin'])->name('proses.login');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('article', ArticleController::class);
    Route::get('/', [ArticleController::class, 'index']);
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $table = 'article';
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Api/ArticleApiController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Article;
use Illuminate\Support\Facades\Cache;

class ArticleApiController extends Controller
{
    public function index(Request $request){
        $data = Article::orderBy('id', 'desc')->paginate();
        return response()->json($data);
    }

}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Events\ArticleEvent;
use Illuminate\Http\Request;
use App\Models\Article;
use App\Http\Requests\StoreArticle;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Cache;

class ArticleController extends Controller
{
    public function index(Request $request){
        $article = Article::orderBy('id', 'desc')->paginate(10);
        return view('pages.index', compact('article'));
    }

    public function store(StoreArticle $request){
        $article = new Article();
        $article->title = $request->title;
        $article->content = $request->content;
        $article->creator = $request->creator;

        $file = $request->file('image');
        $file_extension = $file->extension();
        $filename = rand(0, 99).time().'.'.$file_extension;
        $file->storeAs('public/images', $filename);
        //file path image upload
        $file_path = "storage/app/public/images/{$filename}";
        $fileServerpath = asset($file_path);
        $article->path = $fileServerpath;
        $article->image = $filename;

        $article->save();

        ArticleEvent::dispatch($article);

        return redirect('/article')->with('success', 'Article Uploaded successfully.');

    }

    public function edit($id){
        $article = Article::find($id);
        return view('pages.edit', compact('article'));
    }

    public function update(Request $request, $id){
        $article = Article::find($id);
        $article->title = $request->title;
        $article->content = $request->content;
        $article->creator = $request->creator;

        if (!empty($request->file('image'))) {
            $file = $request->file('image');
            $file_extension = $file->extension();
            $filename = rand(0, 99).time().'.'.$file_extension;
            $file->storeAs('public/images', $filename);
            //file path image upload
            $file_path = "storage/app/public/images/{$filename}";
            $fileServerpath = asset($file_path);
            $article->path = $fileServerpath;
            $article->image = $filename;
        }

        $article->save();

        return redirect('/article')->with('success', 'Article Updated successfully.');
    }

    public function destroy($id){

        $article = Article::find($id);

        if (!empty($article->image)) {
            Storage::delete('public/images/'. $article->image);
        }

        $article->delete();

        return redirect('/article')->with('success', 'Article Deleted successfully.');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LoginController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Auth;

use Illuminate\Http\Request;

class LoginController extends Controller
{
    public function login(){
        return view('login');
    }

    public function prosesLogin(Request $request){
        $request->validate([
            'email' => 'required',
            'password' => 'required',
        ]);
        if (Auth::attempt(['email' => $request->email, 'password' => $request->password])) {
            $request->session()->regenerate();
            return redirect()->intended('/article');
        }else{
            return redirect()->intended('/login');
        }

        return back()->withErrors([
            'password' => 'Wrong email or password',
        ]);
    }

    public function logout(Request $request){
        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();
        return redirect('/login');
    }
}

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Project App Admin</title>

    <link rel="stylesheet" href="{{ asset('public/assets/vendors/mdi/css/materialdesignicons.min.css')}}">
    <link rel="stylesheet" href="{{ asset('public/assets/vendors/css/vendor.bundle.base.css')}}">
    <link rel="stylesheet" href="{{ asset('public/assets/css/style.css')}}">

    <link rel="shortcut icon" href="{{ asset('public/assets/images/favicon.ico')}}" />
</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="content-wrapper d-flex align-items-center auth">
                <div class="row flex-grow">
                    <div class="col-lg-4 mx-auto">
                        <div class="auth-form-light text-left p-5">
                            <h4>Hello! let's get started</h4>
                            <h6 class="font-weight-light">Sign in to continue.</h6>
                            @if(session('success'))
                            <p class="alert alert-success">{{ session('success') }}</p>
                            @endif
                            @if($errors->any())
                            @foreach($errors->all() as $err)
                            <p class="alert alert-danger">{{ $err }}</p>
                            @endforeach
                            @endif
                            <form class="pt-3" action="{{ route('proses.login')}}" method="POST">
                                @csrf
                                <div class="form-group">
                                    <input type="email" class="form-control form-control-lg" id="exampleInputEmail1" placeholder="Username" name="email">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control form-control-lg" id="exampleInputPassword1" placeholder="Password" name="password">
                                </div>
                                <div class="mt-3">
                                    <button type="submit" class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn">
                                        SIGN IN
                                    </button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{ asset('public/assets/vendors/js/vendor.bundle.base.js')}}"></script>
    <script src="{{ asset('public/assets/js/off-canvas.js')}}"></script>
    <script src="{{ asset('public/assets/js/hoverable-collapse.js')}}"></script>
    <script src="{{ asset('public/assets/js/misc.js')}}"></script>

</body>
</html>

resources/views/master/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GO Kampus</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{{ asset('public/assets/vendors/mdi/css/materialdesignicons.min.css')}}">
    <link rel="stylesheet" href="{{ asset('public/assets/vendors/css/vendor.bundle.base.css')}}">

    <link rel="stylesheet" href="{{ asset('public/assets/css/style.css')}}">
    <link rel="shortcut icon" href="{{ asset('public/assets/images/favicon.ico')}}"/>

</head>

<body>
    <div class="container-scroller">

        <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo" href="index.html"><img src="{{ asset('public/assets/images/logo.svg')}}" alt="logo" /></a>
                <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{{ asset('public/assets/images/logo-mini.svg')}}" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-stretch">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="mdi mdi-menu"></span>
                </button>

                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                            <div class="nav-profile-img">
                                <img src="{{ asset('public/assets/images/faces/face1.jpg')}}" alt="image">
                                <span class="availability-status online"></span>
                            </div>
                            <div class="nav-profile-text">
                                <p class="mb-1 text-black">{{ Auth::user()->name }}</p>
                            </div>
                        </a>
                        <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                            <a class="dropdown-item" href="#">

                                <a class="dropdown-item" href="{{route('logout')}}">
                                    <i class="mdi mdi-logout me-2 text-primary"></i> Signout </a>
                                </div>
                            </li>

                        </ul>
                        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                            <span class="mdi mdi-menu"></span>
                        </button>
                    </div>
                </nav>

                <div class="container-fluid page-body-wrapper">

                    <nav class="sidebar sidebar-offcanvas" id="sidebar">
                        <ul class="nav">
                            <li class="nav-item nav-profile">
                                <a href="#" class="nav-link">
                                    <div class="nav-profile-image">
                                        <img src="{{ asset('public/assets/images/faces/face1.jpg')}}" alt="profile">
                                        <span class="login-status online"></span>

                                    </div>
                                    <div class="nav-profile-text d-flex flex-column">
                                        <span class="font-weight-bold mb-2">{{ Auth::user()->name }}</span>
                                        {{-- <span class="text-secondary text-small">Project Manager</span>  --}}
                                    </div>
                                    <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="index.html">
                                    <span class="menu-title">Dashboard</span>
                                    <i class="mdi mdi-home menu-icon"></i>
                                </a>
                            </li>

                        </ul>
                    </nav>
                    <!-- partial -->
                    <div class="main-panel">

                        @yield('content')

                        <footer class="footer">
                            <div class="container-fluid d-flex justify-content-between">
                                <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © bootstrapdash.com 2021</span>
                                <span class="float-none float-sm-end mt-1 mt-sm-0 text-end"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin template</a> from Bootstrapdash.com</span>
                            </div>
                        </footer>
                        <!-- partial -->
                    </div>
                </div>
            </div>


            <script src="{{ asset('public/assets/vendors/js/vendor.bundle.base.js')}}"></script>
            <script src="{{ asset('public/assets/vendors/chart.js/Chart.min.js')}}"></script>
            <script src="{{ asset('public/assets/js/jquery.cookie.js" type="text/javascript')}}"></script>
            <script src="{{ asset('public/assets/js/off-canvas.js')}}"></script>
            <script src="{{ asset('public/assets/js/hoverable-collapse.js')}}"></script>
            <script src="{{ asset('public/assets/js/misc.js')}}"></script>
            <script src="{{ asset('public/assets/js/dashboard.js')}}"></script>
            <script src="{{ asset('public/assets/js/todolist.js')}}"></script>

            <script src="{{asset('public/assets/ckeditor/ckeditor.js')}}"></script>
            <script>
            var konten = document.getElementById("konten");
                CKEDITOR.replace(konten,{
                language:'en-gb'
            });
            CKEDITOR.config.allowedContent = true;
            </script>
        </body>
        </html>

resources/views/pages/edit.blade.php
@extends('master.layout')

@section('content')
<div class="content-wrapper">

    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            @if(Session::has('success'))
            <div class="alert alert-success">
                {{ Session::get('success') }}
                @php
                Session::forget('success');
                @endphp
            </div>
            @endif
            <div class="card-body">
                <h4 class="card-title">Edit Article</h4>
                <br/>
                <form method="POST" class="forms-sample row g-3" action="{{ route('article.update', $article->id)}}" enctype='multipart/form-data'>
                    @csrf
                    @method('put')
                    <div class="form-group col-md-6">
                        <label for="">Upload Image</label>
                        <input type="file" name="image" id="inputImage" class="form-control @error('image') is-invalid @enderror">
                        <span>{{$article->image}}</span>

                        @error('image')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group col-md-6">
                        <label for="">Creator</label>
                        <input type="text" name="creator" id="inputCreator" class="form-control @error('creator') is-invalid @enderror" value="{{$article->creator}}">

                        @error('image')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group col-md-12">
                        <label for="">Title</label>
                        <input type="text" class="form-control" id="" placeholder="Title" name="title" >
                        <input type="text" name="title" id="inputTitle" class="form-control @error('title') is-invalid @enderror" value="{{$article->title}}">

                        @error('title')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group col-md-12">
                        <label for="exampleTextarea1">Textarea</label>
                        <textarea id="konten" class="form-control @error('content') is-invalid @enderror" name="content" rows="10" cols="50">{!! $article->content !!}</textarea>

                        @error('content')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-gradient-primary me-2">Submit</button>
                        <button class="btn btn-light">Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
@endsection

resources/views/pages/index.blade.php
@extends('master.layout')

@section('content')

<div class="content-wrapper">

    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            @if(Session::has('success'))
            <div class="alert alert-success">
                {{ Session::get('success') }}
                @php
                Session::forget('success');
                @endphp
            </div>
            @endif
            <div class="card-body">
                <h4 class="card-title">Data Article</h4>
                <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Tambah
                </button>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th> Article Image </th>
                            <th> Article Creator </th>
                            <th> Title </th>
                            <th> Content </th>
                            <th> Action </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($article as $key => $item )

                        <tr>
                            <td>{{$key + 1}}</td>
                            <td class="py-1">
                                <img src="{{$item->path}}" alt="image" />
                            </td>
                            <td>{{$item->title}}</td>
                            <td>{{$item->creator}}</td>
                            <td>
                                <details>
                                    <summary>click</summary>
                                    {!! $item->content !!}
                                </details>
                            </td>
                            <td>
                                <form action="{{ route('article.destroy', $item->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <a href="{{ route('article.edit', $item->id) }}"
                                        class="btn btn-sm btn-info">
                                        <i class="mdi mdi-table-edit"></i>
                                    </a>
                                    <button type="submit" class="btn btn-sm btn-danger"
                                    onclick="return confirm('Apakah Anda Yakin?')">
                                    <i class="mdi mdi-table-row-remove"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <p>{!! $article->withQueryString()->links('pagination::bootstrap-5') !!}</p>
        </div>

    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-body">
                <div class="col-12 grid-margin stretch-card">

                    <div class="card">
                        <div class="modal-header">
                            <h4 class="card-title">Add Article</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="card-body">
                            <form method="POST" class="forms-sample row g-3" action="{{ route('article.store')}}" enctype='multipart/form-data'>
                                @csrf
                                <div class="form-group col-md-6">
                                    <label for="">Upload Image</label>
                                    <input type="file" name="image" id="inputImage" class="form-control @error('image') is-invalid @enderror">

                                    @error('image')
                                    <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>

                                <div class="form-group col-md-6">
                                    <label for="">Creator</label>
                                    <input type="text" name="creator" id="inputCreator" class="form-control @error('creator') is-invalid @enderror" placeholder="creator sample">

                                    @error('creator')
                                    <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>

                                <div class="form-group col-md-12">
                                    <label for="">Title</label>
                                    <input type="text" name="title" id="inputTitle" class="form-control @error('title') is-invalid @enderror" placeholder="title sample">

                                    @error('title')
                                    <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>

                                <div class="form-group col-md-12">
                                    <label for="exampleTextarea1">Textarea</label>
                                    <textarea id="konten" class="form-control @error('content') is-invalid @enderror" name="content" rows="10" cols="50"></textarea>

                                    @error('content')
                                    <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>

                                <div class="form-group col-md-12">
                                    <button type="submit" class="btn btn-gradient-primary me-2">Submit</button>
                                    <button class="btn btn-light">Cancel</button>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</div>

@endsection